### ISSUE TITLE
mysql error "Access denied for user..."

### ISSUE THREAD

**Issue by jonathandfitzgerald** [Bookworm-project/BookwormDB#101]
When attempting to build my bookworm, I get the following error: 

`fitz@fitz-Macmini:~/Projects/Viral-Texts-Bookworm$ make
bookworm init
bookworm build all
make[1]: Entering directory `/home/fitz/Projects/Viral-Texts-Bookworm'
/usr/local/lib/python2.7/dist-packages/bookwormDB-0.4.0-py2.7.egg/bookwormDB/etc/bookworm_Makefile:85: bookworm -l WARNING -d vt_bookworm tokenize text_stream | parallel --block-size 100M --pipe bookworm -l WARNING -d vt_bookworm tokenize token_stream | bookworm -l WARNING -d vt_bookworm tokenize word_db
/usr/local/lib/python2.7/dist-packages/bookwormDB-0.4.0-py2.7.egg/bookwormDB/etc/bookworm_Makefile:125: bookworm -l WARNING -d vt_bookworm tokenize text_stream | parallel --block-size 100M -u --pipe bookworm -l WARNING -d vt_bookworm tokenize encode
bookworm -l WARNING -d vt_bookworm tokenize text_stream | parallel --block-size 100M --pipe bookworm -l WARNING -d vt_bookworm tokenize token_stream | bookworm -l WARNING -d vt_bookworm tokenize word_db
make -f /usr/local/lib/python2.7/dist-packages/bookwormDB-0.4.0-py2.7.egg/bookwormDB/etc/bookworm_Makefile .bookworm/metadata/jsoncatalog_derived.txt
make[2]: Entering directory `/home/fitz/Projects/Viral-Texts-Bookworm'
/usr/local/lib/python2.7/dist-packages/bookwormDB-0.4.0-py2.7.egg/bookwormDB/etc/bookworm_Makefile:85: bookworm -l WARNING -d vt_bookworm tokenize text_stream | parallel --block-size 100M --pipe bookworm -l WARNING -d vt_bookworm tokenize token_stream | bookworm -l WARNING -d vt_bookworm tokenize word_db
/usr/local/lib/python2.7/dist-packages/bookwormDB-0.4.0-py2.7.egg/bookwormDB/etc/bookworm_Makefile:125: bookworm -l WARNING -d vt_bookworm tokenize text_stream | parallel --block-size 100M -u --pipe bookworm -l WARNING -d vt_bookworm tokenize encode
cat .bookworm/metadata/jsoncatalog.txt | parallel --pipe bookworm -l WARNING -d vt_bookworm prep catalog_metadata > .bookworm/metadata/jsoncatalog_derived.txt
make[2]: Leaving directory `/home/fitz/Projects/Viral-Texts-Bookworm'
make -f /usr/local/lib/python2.7/dist-packages/bookwormDB-0.4.0-py2.7.egg/bookwormDB/etc/bookworm_Makefile .bookworm/texts/textids.dbm
make[2]: Entering directory `/home/fitz/Projects/Viral-Texts-Bookworm'
/usr/local/lib/python2.7/dist-packages/bookwormDB-0.4.0-py2.7.egg/bookwormDB/etc/bookworm_Makefile:85: bookworm -l WARNING -d vt_bookworm tokenize text_stream | parallel --block-size 100M --pipe bookworm -l WARNING -d vt_bookworm tokenize token_stream | bookworm -l WARNING -d vt_bookworm tokenize word_db
/usr/local/lib/python2.7/dist-packages/bookwormDB-0.4.0-py2.7.egg/bookwormDB/etc/bookworm_Makefile:125: bookworm -l WARNING -d vt_bookworm tokenize text_stream | parallel --block-size 100M -u --pipe bookworm -l WARNING -d vt_bookworm tokenize encode
bookworm -l WARNING -d vt_bookworm prep preDatabaseMetadata
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/fitz/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
bookworm -l WARNING -d vt_bookworm prep text_id_database
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/fitz/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
make[2]: Leaving directory `/home/fitz/Projects/Viral-Texts-Bookworm'
make -f /usr/local/lib/python2.7/dist-packages/bookwormDB-0.4.0-py2.7.egg/bookwormDB/etc/bookworm_Makefile .bookworm/metadata/catalog.txt
make[2]: Entering directory `/home/fitz/Projects/Viral-Texts-Bookworm'
/usr/local/lib/python2.7/dist-packages/bookwormDB-0.4.0-py2.7.egg/bookwormDB/etc/bookworm_Makefile:85: bookworm -l WARNING -d vt_bookworm tokenize text_stream | parallel --block-size 100M --pipe bookworm -l WARNING -d vt_bookworm tokenize token_stream | bookworm -l WARNING -d vt_bookworm tokenize word_db
/usr/local/lib/python2.7/dist-packages/bookwormDB-0.4.0-py2.7.egg/bookwormDB/etc/bookworm_Makefile:125: bookworm -l WARNING -d vt_bookworm tokenize text_stream | parallel --block-size 100M -u --pipe bookworm -l WARNING -d vt_bookworm tokenize encode
make[2]: `.bookworm/metadata/catalog.txt' is up to date.
make[2]: Leaving directory `/home/fitz/Projects/Viral-Texts-Bookworm'
bookworm -l WARNING -d vt_bookworm tokenize text_stream | parallel --block-size 100M -u --pipe bookworm -l WARNING -d vt_bookworm tokenize encode
touch .bookworm/targets/encoded
bookworm -l WARNING -d vt_bookworm prep database_wordcounts
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/fitz/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
17/2016 20:29:23:ERROR:Query failed: 
DROP TABLE IF EXISTS words

Traceback (most recent call last):
  File "/usr/local/bin/bookworm", line 9, in <module>
    load_entry_point('bookwormDB==0.4.0', 'console_scripts', 'bookworm')()
  File "/usr/local/lib/python2.7/dist-packages/bookwormDB-0.4.0-py2.7.egg/bookwormDB/manager.py", line 558, in run_arguments
    getattr(my_bookworm,args.action)(args)
  File "/usr/local/lib/python2.7/dist-packages/bookwormDB-0.4.0-py2.7.egg/bookwormDB/manager.py", line 228, in prep
    getattr(self,args.goal)()
  File "/usr/local/lib/python2.7/dist-packages/bookwormDB-0.4.0-py2.7.egg/bookwormDB/manager.py", line 372, in database_wordcounts
    Bookworm.load_word_list()
  File "/usr/local/lib/python2.7/dist-packages/bookwormDB-0.4.0-py2.7.egg/bookwormDB/CreateDatabase.py", line 209, in load_word_list
    db.query("""DROP TABLE IF EXISTS words""")
  File "/usr/local/lib/python2.7/dist-packages/bookwormDB-0.4.0-py2.7.egg/bookwormDB/CreateDatabase.py", line 104, in query
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/bookwormDB-0.4.0-py2.7.egg/bookwormDB/CreateDatabase.py", line 74, in connect
    self.conn = MySQLdb.connect(read_default_file="~/.my.cnf",use_unicode='True', charset='utf8', db='', local_infile=1)
  File "build/bdist.linux-x86_64/egg/MySQLdb/__init__.py", line 81, in Connect
  File "build/bdist.linux-x86_64/egg/MySQLdb/connections.py", line 193, in __init__
_mysql_exceptions.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
make[1]: *** [.bookworm/targets/database_wordcounts] Error 1
make[1]: Leaving directory `/home/fitz/Projects/Viral-Texts-Bookworm'`

**Comment by bmschmidt** [comment]
So I think "Access denied for user 'root'@'localhost" is indicating that you don't have any mysql access set up for the user defined in `.my.cnf`, or that you don't have that file at all.

One test here would be: can you type `mysql` in the terminal to log into a local mysql console?

Do you then have the permissions to run
```
"CREATE DATABASE test";
"GRANT ALL ON test.* to 'nobody'@'localhost' IDENTIFIED BY 'thispassworddoesntmatter'"
```

If not, try running `bookworm config mysql`

**Comment by jonathandfitzgerald** [comment]
Hmm. I do have a root user set up with access and defined in .my.cnf. I ran the test as you suggested and it was successful. I also checked the permissions of the user (I'm using root, so it should have all privileges) and it all looked good.

**Comment by jonathandfitzgerald** [comment]
Here's something interesting: when I run `bookworm config mysql` and follow the prompt `Please enter an *administrative* username for your mysql with grant privileges:` and I use "root," it returns `No username found for the user in the global role`. But, of course, that user is there in the global role (right?).

**Comment by bmschmidt** [comment]
Hmm. It is hard to debug this without seeing which files are where. But I can't see how the presence of this error
`_mysql_exceptions.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")` can mean anything other than that the configuration files are still wrong.

One possibility is that the file at `~/.my.cnf` is missing some sections. It should look like this

```
[client]
user=bschmidt
host=localhost
password=Your secret password
```

Or maybe trying to use `root` as your administrative user is screwing things up somehow. I'd try using `bookworm config mysql` and don't just re-enter the 'root' information for the 'admin' user: use "admin" and "password," or something like that.

**Comment by jonathandfitzgerald** [comment]
Okay. Progress. I tried your suggestion at the end of your last post and didn't use `root` and instead created a new admin user for mysql. This allowed me to build without errors. Then, however, when I tried `bookworm serve`, I get the same operational error as above. What's interesting is that it here it is still trying to use `'root'@'localhost'` even though the new user should be `'bwadmin'@'localhost'`. I checked both the bookworm.cnf and `~/.my.cnf` and they both use `bwadmin`. I'm not sure where it's still holding on to `root`.

**Comment by jonathandfitzgerald** [comment]
Oh, I think I see where. I get the following error: `ERROR:root:/etc/mysql/my.cnf` and `ERROR:root:Database error`. I thought it would use `~/.my.cnf` over the one in `/etc/mysql/my.cnf`, no?

**Comment by jonathandfitzgerald** [comment]
I changed the user in `/etc/mysql/my.cnf` to `bwadmin` and that seems to have solved the problem. I was worried that it would mess up other things that use mysql (I also have a worpdress site hosted on this server), but it all seems to be working. So that's good. Thanks for the help on this.

**Comment by bmschmidt** [comment]
Another user reported a similar issue.

Here's a magical set of invocations that can work in an EC2-like environment:

(from the repo directory)

``` sh
# Make sure that you have access.
mysql -e "CREATE DATABASE temporary_test"
mysql -e "DROP DATABASE temporary_test"
pip install .
sudo pip install .
bookworm config --force mysql
# Enter admin password as prompted.
```

**Comment by triplingual** [comment]
My install was in a state that the first `mysql -e` failed even the access threshold. Looking in `mysql.user`, somewhere along the line (my notes are good enough for me to do this again, I think, but not perfect so I don't have better info on that crux), my allegedly all-privileges user was created with only `USAGE` rights. So I fixed that with `GRANT ALL ON *.*` etc. The pip installs work fine, but then a flop on the last line. It's using `root`, but never asks me for a pw, so fails.

Stack trace, if it helps:

	Using sudo to process password change(s) for global. The system may now request your root password.
	Creating config files in /etc/bookworm.
	This may require an admin password.
	Traceback (most recent call last):
	  File "/usr/local/bin/bookworm", line 9, in <module>
		load_entry_point('bookwormDB==0.4.0', 'console_scripts', 'bookworm')()
	  File "/usr/local/lib/python2.7/dist-packages/bookwormDB-0.4.0-py2.7.egg/bookwormDB/manager.py", line 567, in run_arguments
		getattr(my_bookworm,args.action)(args)
	  File "/usr/local/lib/python2.7/dist-packages/bookwormDB-0.4.0-py2.7.egg/bookwormDB/manager.py", line 76, in config
		bookwormDB.configuration.reconfigure_passwords(args.users,args.force)
	  File "/usr/local/lib/python2.7/dist-packages/bookwormDB-0.4.0-py2.7.egg/bookwormDB/configuration.py", line 398, in reconfigure_passwords
		update_settings_for(name,force=force)
	  File "/usr/local/lib/python2.7/dist-packages/bookwormDB-0.4.0-py2.7.egg/bookwormDB/configuration.py", line 357, in update_settings_for
		client.change_client_password()
	  File "/usr/local/lib/python2.7/dist-packages/bookwormDB-0.4.0-py2.7.egg/bookwormDB/configuration.py", line 212, in change_client_password
		db = MySQLdb.connect(user="root",passwd="",host="127.0.0.1")
	  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
		return Connection(*args, **kwargs)
	  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 193, in __init__
		super(Connection, self).__init__(*args, **kwargs2)
	_mysql_exceptions.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: NO)")

**Comment by bmschmidt** [comment]
Interesting. Yeah, it's assuming that the mysql root password is blank. 

If you try `bookworm config mysql` (ie, without the --force) it should ask for the password interactively.

Alternatively, on a VM, you could [Root up your existing mysql installation](http://stackoverflow.com/questions/10853004/removing-mysql-5-5-completely) and start over.

**Comment by triplingual** [comment]
Oh, I'm on my third uprooting of MySQL. :-D

Realized I should try to follow that stack trace myself and got to line 212 in configuration.py, saw that bit about trying root with a blank pw, so I went in to mysql and blanked root's pw, flushed privileges and then the config forcing mysql worked. It threw up a warning about no config file at /etc/bookworm/admin.cnf, but running the command again as sudo then again without sudo seemed to work. Incantations ahoy!

Currently debugging an endless spinning wheel on a test of the Federalist repo (or Simpsons, perhaps), so progress.
