### ISSUE TITLE
Strip trailing whitespace

### ISSUE THREAD

**Issue by organisciak** [Bookworm-project/BookwormDB#105]
Sometimes HT+BW users search with inadvertent trailing whitespace, which pings the API as "word+" instead of "word". This fails.

I expect correcting for this can be done on the client or the API side, but since it's a safe assumption that the trailing whitespace is *never* desired, I propose fixing it in here rather than the client.

I can write this fix, if @bmschmidt is on board.

**Comment by bmschmidt** [comment]
Thanks, good idea. I think this is a safe assumption, but just to be *super* safe can I scope it down to just the traditional space character, not other forms of whitespace. (The formfeed character can mean something in bigrams; and we could leave the no-break space open for anyone who wanted to hack on the margins here. If you want to kill `\n` and `\r` as well, that's probably fine.)

Also, preceding spaces should also be deleted. Those sometimes creep in in the formats that allow comma-joined lists of words.

**Comment by organisciak** [comment]
I'm somewhat confused as this how this works. I'm testing on the Congress dataset, which has a bigram table unlike HT+BW. Here's what I get for TextCount, for sponsor_state = WA:

Search Limit for word | TextCount for WA | WordCount | Notes
------------- | ---------- | -------- | ----
"word":["United"]  |  1019 | 2094 |
"word":["United "]  |  1019 | 2094 |
"word":["United States"]  |  1015 | 2071 |
"word":["United States "]  |  4134 | 1118396 | This is everything
"word":["United States of"]  |  4134 | 1118396 |

Adding the space on a unigram for a bigram index keeps things the same, but adding it onto a bigram seems to break things. Returning everything is BW's (current) response to being asked for more ngrams than are indexed. 

My guess is that the trailing space is being interpreted as preceding a (zero-character, non-existent) word, as in `["word1", ""]` but if `len(words)` is less than the indexed `n`, Bookworm figures out to ignore the empty word. If `len(words)` is too high, that's where it fails. I'll have to go in the code to confirm this, but I can see that *two* trailing spaces on a unigram does break the response:

```
Search     | TextCount | WordCount | Notes
---------- | --------- | --------- | -------
"United  " |  4134     | 1118396   | Two trailing spaces
```

**Comment by bmschmidt** [comment]
Yes, I think you're right about the problem. The API does a split [here](https://github.com/Bookworm-project/BookwormDB/blob/master/bookwormDB/SQLAPI.py#L484).

The reason it returns everything is that the API implementation [attaches needed tables to the query](https://github.com/Bookworm-project/BookwormDB/blob/master/bookwormDB/SQLAPI.py#L544-L546) based on how long the tokenized list is. If it's one word it attaches the 'master_bookcounts' table; if two, the 'master_bigrams' table. If it's three, it doesn't attach *anything* and so proceeds merrily along with summary statistics, I guess. That linked block would be a reasonable place to test and throw one of your new errors.

**Comment by organisciak** [comment]
I was *just* about push a fix, without realizing the obvious fix: `phrase.split()`, which splits on 1 or more spaces. Occam's razor and all that. This fixes preceding and following spaces, and double spaces between words. Simple enough that I pushed straight to master.

Is your approach to testing figured out? Does this need a test written first, or are we safe to close?

**Comment by bmschmidt** [comment]
Thanks for the fix. Yeah, that should be fine. Not sure why I didn't use straight 'split' to begin with. I haven't yet sat down to try and make this run on Travis, so I'm happy to close.
