### ISSUE TITLE
Makefile dependency

### ISSUE THREAD

**Issue by organisciak** [Bookworm-project/BookwormDB#131]
`.bookworm/targets/database_metadata` shouldn't depend on `.bookworm/targets/database_wordcounts`, right? As far as I care tell, they're orthoginal.

https://github.com/Bookworm-project/BookwormDB/blob/master/bookwormDB/etc/bookworm_Makefile#L149

**Comment by bmschmidt** [comment]
IIRC, `database_metadata` includes wordcounts; so it needs the `nwords` table; and the `nwords` table is assembled out of the `master_bookcounts` table.

**Comment by organisciak** [comment]
Thank you.
