### ISSUE TITLE
manager.py logging broken

### ISSUE THREAD

**Issue by organisciak** [Bookworm-project/BookwormDB#133]
By the time you set loglevel with `bookworm -l`, the logger is already initialized, so it needs to be retrieved to change the settings. `basicConfig` only works when initializing a logger, not for updating an existing one.

This is an FYI issue. I have a fix staged where I keep the logger from initializing before argument parsing.

**Comment by bmschmidt** [comment]
Ah, that explains a lot. Thanks.
