### ISSUE TITLE
Installing on shared space with virtualenv

### ISSUE THREAD

**Issue by apdame** [Bookworm-project/BookwormDB#140]
So I'm trying to install bookworm on a shared server space using a virtualenv, but I keep hitting a permissions error when I get to the dbbindings.py file ([Errno 13] Permission denied: ‘/var/www/cgi-bin/dbbindings.py’). This issue appears to have been discussed in #115, but I couldn't tell if the workaround had been implemented. 

If it hasn't been, is there a good suggestion for how to manually reset the memory tables? That's basically all I need the install for, but in reading the code I wasn't able to parse the exact reset process.

**Comment by apdame** [comment]
It should, though I think I might need to pre-define "client." Here's the traceback I get from trying to run the command:

Traceback (most recent call last):
  File "manager.py", line 570, in <module>
    run_arguments()
  File "manager.py", line 567, in run_arguments
    getattr(my_bookworm,args.action)(args)
  File "manager.py", line 325, in reload_memory
    Bookworm = bookwormDB.CreateDatabase.BookwormSQLDatabase(database,variableFile=None)
  File "/home/queerdig/virtualenv/BookwormDB/2.7/lib/python2.7/site-packages/bookwormDB/CreateDatabase.py", line 153, in __init__
    self.dbname = config.get("client","database")
  File "/opt/alt/python27/lib64/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'client'

**Comment by bmschmidt** [comment]
OK. Yeah, it's trying to find a mysql configuration file with passwords for the db and not turning one up.

Probably the code should just be trying to log in without credentials--this may be worth changing later.
 Maybe it would work with a `--database` argument to the reload command.

If not, try putting a file at either (or both) `~/.my.cnf` OR `bookworm.cnf` in the directory you're working out of which has passwords in it: that should look something like this, although the values will be different.

```
[client]
database = federalist
password = password123
user = bschmidt
```

**Comment by bmschmidt** [comment]
Hmm. This is tough to reproduce, and that time would be probably be better spent on the general issue.

If you just want to get memory tables reloaded on one installation, the barest way to do this is pull the code to update memory tables directly out of the database. When logged into your db in mysql, type:

```sql
SELECT memoryCode FROM masterTableTable;
```

That should yield a bunch of SQL code you can run there, or run `SELECT  memoryCode FROM masterTableTable INTO OUTFILE '/tmp/code.sql'` instead and you'll get a file at /tmp/code.sql that you can run whenever desired.

**Comment by apdame** [comment]
Yeah, agreed. I may fiddle with it when I get time, but otherwise I'm going to go ahead and close this issue. Thanks for following up on this (seeming) fools' errand!
