### ISSUE TITLE
query raises an error if groups is an empty list

### ISSUE THREAD

**Issue by chrissbarnett** [Bookworm-project/BookwormDB#141]
I had an issue where a query to bookworm with the group param set to [] resulted in an error:
`{"message":"Database error. Try checking field names.","status":"error"}`

Following the stack trace led to 'fixNumpyType' in 'general_API.py', which was raising an exception because ` 'int' object has no attribute 'dtype'`

In my installation, I modified this method to directly check for the numpy type, and this seemed to resolve the problem.  I'm not 100% sure that this resolves the issue that the method was originally intended to resolve.
```python
import numpy as np
.
.
.
        def fixNumpyType(input):
            # This is, weirdly, an occasional problem but not a constant one.
            if type(input) is np.int64:
                return int(input)
            else:
                return input
```

The numpy and pandas versions I am using:
- numpy           1.15.2   
- pandas          0.23.4

**Comment by bmschmidt** [comment]
Thanks!

This makes sense as a fix. As the comment at the head indicates, this whole code block is a little suspect. Will try push it into the main branch soon.

**Comment by chrissbarnett** [comment]
thanks!
