### ISSUE TITLE
Bookworm install working but drawing blank graph

### ISSUE THREAD

**Issue by tpmccallum** [Bookworm-project/BookwormDB#53]
Hi 
I have written up the installation procedure which I followed (excuse the mess, it is a living document < https://www.gitbook.com/book/tpmccallum/harvesting-pdf-files-from-the-web-for-use-in-book >

I am happy with the installation but there must be an issue because I am getting back an empty JSON object when hitting the following URL

http://54.153.174.142/cgi-bin/dbbindings.py?query=%7B%22groups%22%3A%5B%22date_year%22%5D%2C%22counttype%22%3A%22WordsPerMillion%22%2C%22words_collation%22%3A%22Case_Sensitive%22%2C%22database%22%3A%22mccallum%22%2C%22search_limits%22%3A%5B%7B%22word%22%3A%5B%22test%22%5D%2C%22date_year%22%3A%7B%22%24gte%22%3A2012%2C%22%24lte%22%3A2023%7D%7D%5D%2C%22method%22%3A%22return_json%22%7D

Do you have any advice?
Very happy to give you the Amazon EC2 credential so that you can take a look at the setup.

Kind regards
Tim

**Comment by tpmccallum** [comment]
I see that the query 
> http://54.153.174.142/cgi-bin/dbbindings.py?queryTerms={%22database%22:%22mccallum%22,%22method%22:%22returnPossibleFields%22} returns 
```
[
{
name: "uni",
tablename: "uniLookup",
dbname: "uni",
type: "character",
anchor: "bookid",
description: ""
},
{
name: "date_year",
tablename: "fastcat",
dbname: "date_year",
type: "integer",
anchor: "bookid",
description: ""
}
]
```
However I get this result from the MySQL
```
mysql> select * from fastcat;
Empty set (0.00 sec)

mysql> select * from uniLookup;
Empty set (0.00 sec)
```

**Comment by sa501428** [comment]
Ben had actually helped me with this issue:

After a restart, it's possible that the memory tables haven't been repopulated. The way to test that is to run 

      SELECT COUNT(*) FROM fastcat;

in MySQL. On a modern Bookworm build, that is fixed by running

      python OneClick.py reloadAllMemory

and the whole server will refresh. On the older bookworms, you would need to find the SQL table create code that the OneClick process used to dump out and execute it in MySQL (generally saved as a create_table.SQL).

I'm guessing the former method should solve the issue.

**Comment by tpmccallum** [comment]
Hi,
Thank you again so much for your help, I will add that to my documentation, again really appreciate you assisting with this using your valuable time.

I ended up figuring out what was wrong ... when I ran the 
```
make all databaseName=asdf ...
```
The users did not have database privileges, these issues were resolved here 
```
https://github.com/Bookworm-project/BookwormDB/issues/52
```
I decided to re-run the make command and it all works :)

Chat soon
Tim
