### ISSUE TITLE
Admin user documentation needs GRANT OPTION

### ISSUE THREAD

**Issue by abbymullen** [Bookworm-project/BookwormDB#67]
This issue is being filed by Ben from Abby's machine, where we discovered the problem.

Where the documentation currently reads: 

```SQL
CREATE USER 'foobar'@'localhost' IDENTIFIED BY 'mysecret';
GRANT ALL PRIVILEGES ON *.* TO 'foobar'@'localhost';
FLUSH PRIVILEGES;
```

It seems it should reflect also granting GRANT privileges or the build will break at the end.

```SQL
CREATE USER 'foobar'@'localhost' IDENTIFIED BY 'mysecret';
GRANT ALL PRIVILEGES ON *.* TO 'foobar'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
```

**Comment by bmschmidt** [comment]
Fixed: https://github.com/Bookworm-project/BookwormDB/commit/037bd716525ce076a49d73f2b1d9464d5ece2e89
