### ISSUE TITLE
Automatically reload memory tables

### ISSUE THREAD

**Issue by bmschmidt** [Bookworm-project/BookwormDB#80]
The need to manually reset memory tables is infuriating.

The following line of bash sets a debian server to automatically repopulate the tables for every bookworm on a server. 

On Debian systems, there should be some way to install this automatically.
On OS X, we'd have to design something using launchd which is a whole different process; the same philosophy could apply.

``` bash
echo "@reboot root          sleep 100 && bookworm reload_memory --skip-reload --all >> /etc/cron.d/bookworm
```

The `sleep 100` is a bit of a hack to make it wait for the MySQL server to start up. But attaching something to init.d is a royal, royal pain.

**Comment by organisciak** [comment]
Perhaps a related (documentation) issue, it's not entirely clear that you have to reload tables or when. I was looking up *how* to reload memory tables, and it struck me that new users might not know the *what* - i.e. that it even needs to be done.

**Comment by bmschmidt** [comment]
Yeah noted. Related is the issue here: https://github.com/Bookworm-project/BookwormDB/issues/85 ; it may make sense to have memory tables be a performance-optimization someone must consciously enable.

**Comment by bmschmidt** [comment]
Folded into https://github.com/Bookworm-project/BookwormDB/issues/139
